// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/design-1/Design1.tsx": () => import("../components/mockups/design-1/Design1.tsx"),
  "./components/mockups/design-3/Design3.tsx": () => import("../components/mockups/design-3/Design3.tsx"),
  "./components/mockups/design-4/Design4.tsx": () => import("../components/mockups/design-4/Design4.tsx"),
  "./components/mockups/design-2/Design2.tsx": () => import("../components/mockups/design-2/Design2.tsx"),
  "./components/mockups/design-5/Design5.tsx": () => import("../components/mockups/design-5/Design5.tsx")
};
