// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/design-1/Design1.tsx": () => import("../components/mockups/design-1/Design1.tsx"),
  "./components/mockups/design-1/Design1Ar.tsx": () => import("../components/mockups/design-1/Design1Ar.tsx"),
  "./components/mockups/design-1/Design1En.tsx": () => import("../components/mockups/design-1/Design1En.tsx"),
  "./components/mockups/design-2/Design2.tsx": () => import("../components/mockups/design-2/Design2.tsx"),
  "./components/mockups/design-2/Design2Ar.tsx": () => import("../components/mockups/design-2/Design2Ar.tsx"),
  "./components/mockups/design-2/Design2En.tsx": () => import("../components/mockups/design-2/Design2En.tsx"),
  "./components/mockups/design-3/Design3.tsx": () => import("../components/mockups/design-3/Design3.tsx"),
  "./components/mockups/design-3/Design3Ar.tsx": () => import("../components/mockups/design-3/Design3Ar.tsx"),
  "./components/mockups/design-3/Design3En.tsx": () => import("../components/mockups/design-3/Design3En.tsx"),
  "./components/mockups/design-4/Design4.tsx": () => import("../components/mockups/design-4/Design4.tsx"),
  "./components/mockups/design-4/Design4Ar.tsx": () => import("../components/mockups/design-4/Design4Ar.tsx"),
  "./components/mockups/design-4/Design4En.tsx": () => import("../components/mockups/design-4/Design4En.tsx"),
  "./components/mockups/design-5/Design5.tsx": () => import("../components/mockups/design-5/Design5.tsx"),
  "./components/mockups/design-5/Design5Ar.tsx": () => import("../components/mockups/design-5/Design5Ar.tsx"),
  "./components/mockups/design-5/Design5En.tsx": () => import("../components/mockups/design-5/Design5En.tsx")
};
